# Generated by Django 2.2.12 on 2020-06-09 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('rua', models.CharField(max_length=255)),
                ('area_interesse', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atividade.Aprendiz')),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('CNPJ', models.DecimalField(decimal_places=4, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('Disciplinas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atividade.Disciplinas')),
            ],
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='empresas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atividade.Empresas'),
        ),
    ]
